//
//  LLPositionManager.h
//  LocusLabsSDK
//
//  Created by Samuel Ziegler on 6/16/14.
//  Copyright © 2014-2021 LocusLabs, Inc. All rights reserved.
//  Copyright © 2021 Acuity Brands, Inc. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreLocation/CoreLocation.h>
#import "LLPositionManagerDelegate.h"
#import "LLMapView.h"

/**
 *  The LLPositionManager leverages all available positioning technologies to give as precise a location as possible.
 */
@interface LLPositionManager : NSObject

/**
 *  The delegate to receive events generated by the position manager.
 */
@property (weak,nonatomic) id<LLPositionManagerDelegate> delegate;

/**
 *  The venues are used to gather all of the information needed for indoor positioning.
 */
@property (strong,nonatomic,readonly) NSArray *venues;

/**
 *  Enable or disable active positioning by setting this property to true or false.  Enabling active positioning
 *  will provide positioning with higher accuracy and more frequent updates, but uses significantly more power and resources.  Therefore, it should
 *  only for real-time or precision features such as navigation.  Enabling active positioning implicitly activates passive positioning.
 */
@property (assign,nonatomic) BOOL activePositioning;

/**
 *  Enable or disable passive positioning by setting this property to true or false.  Passive positioning uses minimal
 *  resources and will provide position updates when the application is in the background.
 */
@property (assign,nonatomic) BOOL passivePositioning;

/**
 *  If positioning is available on this device, this is set to true.
 */
@property (assign,nonatomic) BOOL positioningAvailable;


@property (assign,nonatomic) BOOL positioningEnabled __attribute__((deprecated("setting this property has no effect")));;

/**
 *  Constructor.
 *
 *  Different Venues can use different positioning mechanisms, including Beacons,
 *  Core Location and others.  To monitor multiple venues with a single Position Manager
 *  ALL of the venues must use the same mechanism.
 *
 *  Due to this restriction it is recommended that you use a separate Position Manager for each venue individually.
 *
 *  @return the new instance
 */
- (id)initWithVenues:(NSArray*)venues;

/**
 */
- (id)initWithVenuesBeaconsOnly:(NSArray*)venues;

@end
